use_frameworks!

platform :ios, '9.0'

target 'DynamsoftBarcodeReader_Example' do
  pod 'DynamsoftBarcodeReader', :path => '../'

  target 'DynamsoftBarcodeReader_Tests' do
    inherit! :search_paths

    
  end
end
